"""Add issued_at column to Invoice

Revision ID: 026bcefdfce4
Revises: 0e424f983ac3
Create Date: 2025-08-31 15:46:16.542730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '026bcefdfce4'
down_revision: Union[str, Sequence[str], None] = '0e424f983ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('issued_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'issued_at')
    # ### end Alembic commands ###
