"""remove useless check constraint from events table

Revision ID: 0277bd44aa62
Revises: 87d0d9bd10d8
Create Date: 2025-07-24 01:21:40.344050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0277bd44aa62'
down_revision: Union[str, Sequence[str], None] = '87d0d9bd10d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_constraint("chk_sales_vs_event", "events", type_="check")

    op.drop_constraint("chk_event_time_range", "events", type_="check")
    op.create_check_constraint(
        "chk_event_time_range",
        "events",
        "event_end >= event_start"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
