"""Add invoice_number + currency_code to Invoice model

Revision ID: 0e424f983ac3
Revises: 4d5f78986ce1
Create Date: 2025-08-31 15:26:29.294156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e424f983ac3'
down_revision: Union[str, Sequence[str], None] = '4d5f78986ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('invoice_number', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('currency_code', sa.String(length=3), server_default='PLN', nullable=False))
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_column('invoices', 'currency_code')
    op.drop_column('invoices', 'invoice_number')
    # ### end Alembic commands ###
