"""chore: generate migration for payment_methods table

Revision ID: 1860ae7b1c7d
Revises: ff76ae27cdd1
Create Date: 2025-08-21 12:16:14.420283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1860ae7b1c7d'
down_revision: Union[str, Sequence[str], None] = 'ff76ae27cdd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_methods', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_methods', 'is_active')
    # ### end Alembic commands ###
