"""create event ticket type model

Revision ID: 1a47d9f6fbd0
Revises: 40bf5c5338f8
Create Date: 2025-08-07 18:56:12.078688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a47d9f6fbd0'
down_revision: Union[str, Sequence[str], None] = '40bf5c5338f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_ticket_types',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('event_sector_id', sa.Integer(), nullable=False),
    sa.Column('ticket_type_id', sa.Integer(), nullable=False),
    sa.Column('price_net', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.CheckConstraint('price_net >= 0', name='chk_ticket_price'),
    sa.ForeignKeyConstraint(['event_sector_id'], ['event_sectors.id'], ),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_sector_id', 'ticket_type_id', name='uq_event_sector_ticket_type')
    )
    op.create_index(op.f('ix_event_ticket_types_event_sector_id'), 'event_ticket_types', ['event_sector_id'], unique=False)
    op.create_index(op.f('ix_event_ticket_types_ticket_type_id'), 'event_ticket_types', ['ticket_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_ticket_types_ticket_type_id'), table_name='event_ticket_types')
    op.drop_index(op.f('ix_event_ticket_types_event_sector_id'), table_name='event_ticket_types')
    op.drop_table('event_ticket_types')
    # ### end Alembic commands ###
