"""Create EventSector model

Revision ID: 23882574edcd
Revises: 35a4995c1cb2
Create Date: 2025-08-04 13:03:37.005571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23882574edcd'
down_revision: Union[str, Sequence[str], None] = '35a4995c1cb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_sectors',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('tickets_left', sa.Integer(), nullable=True),
    sa.CheckConstraint('tickets_left >= 0', name='chk_tickets_left'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'sector_id', name='uq_event_sector')
    )
    op.create_index(op.f('ix_event_sectors_event_id'), 'event_sectors', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_sectors_sector_id'), 'event_sectors', ['sector_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_sectors_sector_id'), table_name='event_sectors')
    op.drop_index(op.f('ix_event_sectors_event_id'), table_name='event_sectors')
    op.drop_table('event_sectors')
    # ### end Alembic commands ###
