"""remove snapshots from ticket model and add them to ticketinstance model

Revision ID: 3144fec53d31
Revises: 556c98b2f6ad
Create Date: 2025-08-13 01:56:18.815457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3144fec53d31'
down_revision: Union[str, Sequence[str], None] = '556c98b2f6ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_instances', sa.Column('price_net_snapshot', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('ticket_instances', sa.Column('vat_rate_snapshot', sa.Numeric(precision=3, scale=2), nullable=False))
    op.add_column('ticket_instances', sa.Column('price_gross_snapshot', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('tickets', 'price_gross')
    op.drop_column('tickets', 'price_net')
    op.drop_column('tickets', 'vat_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('vat_rate', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False))
    op.add_column('tickets', sa.Column('price_net', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('tickets', sa.Column('price_gross', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('ticket_instances', 'price_gross_snapshot')
    op.drop_column('ticket_instances', 'vat_rate_snapshot')
    op.drop_column('ticket_instances', 'price_net_snapshot')
    # ### end Alembic commands ###
