"""create seat model

Revision ID: 35a4995c1cb2
Revises: be33eea6578f
Create Date: 2025-08-04 01:25:06.829664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a4995c1cb2'
down_revision: Union[str, Sequence[str], None] = 'be33eea6578f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seats',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.CheckConstraint('number > 0', name='chk_seat_number_gt0'),
    sa.CheckConstraint('row > 0', name='chk_seat_row_gt0'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sector_id', 'row', 'number', name='uq_sector_seat_row_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seats')
    # ### end Alembic commands ###
