"""address_id now required for Organizer

Revision ID: 35e8bd92c3a0
Revises: 4a52556878ce
Create Date: 2025-09-08 20:19:33.458237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35e8bd92c3a0'
down_revision: Union[str, Sequence[str], None] = '4a52556878ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizers', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('organizers_address_id_fkey'), 'organizers', type_='foreignkey')
    op.create_foreign_key(None, 'organizers', 'addresses', ['address_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizers', type_='foreignkey')
    op.create_foreign_key(op.f('organizers_address_id_fkey'), 'organizers', 'addresses', ['address_id'], ['id'], ondelete='SET NULL')
    op.alter_column('organizers', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
