"""add default value for reserved_until in Order

Revision ID: 4a52556878ce
Revises: 44fac9664860
Create Date: 2025-09-04 01:47:24.020187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a52556878ce'
down_revision: Union[str, Sequence[str], None] = '44fac9664860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'reserved_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc', now()) + interval '20 minutes'"),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'reserved_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
