"""Add ticket type snapshot column to TicketInstance

Revision ID: 4d5f78986ce1
Revises: 4799a4f65ff9
Create Date: 2025-08-30 15:29:47.826741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d5f78986ce1'
down_revision: Union[str, Sequence[str], None] = '4799a4f65ff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_instances', sa.Column('ticket_type_name_snapshot', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_instances', 'ticket_type_name_snapshot')
    # ### end Alembic commands ###
