"""changed ORM model to Table for N:M relationships

Revision ID: 65f25dcc548b
Revises: e1be939f0185
Create Date: 2025-07-15 18:49:51.025404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f25dcc548b'
down_revision: Union[str, Sequence[str], None] = 'e1be939f0185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
