"""add events table, modify defaults in organizers

Revision ID: 7df0564a7403
Revises: 95f5574098f4
Create Date: 2025-07-23 19:25:54.186054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7df0564a7403'
down_revision: Union[str, Sequence[str], None] = '95f5574098f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('event_start', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('event_end', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('sales_start', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('sales_end', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('max_tickets_per_user', sa.Integer(), nullable=True),
    sa.Column('age_restriction', sa.Integer(), nullable=False),
    sa.Column('holder_data_required', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ON_SALE', 'ENDED', 'CANCELLED', name='event_status'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('event_end > event_start', name='chk_event_time_range'),
    sa.CheckConstraint('sales_end <= event_start', name='chk_sales_vs_event'),
    sa.CheckConstraint('sales_end >= sales_start', name='chk_sales_range'),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_organizer_id'), 'events', ['organizer_id'], unique=False)
    op.create_index(op.f('ix_events_venue_id'), 'events', ['venue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_venue_id'), table_name='events')
    op.drop_index(op.f('ix_events_organizer_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
