"""change column to is_active in sectors table

Revision ID: 842e7c11e486
Revises: fd2a58eb98d0
Create Date: 2025-07-22 00:35:29.029934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842e7c11e486'
down_revision: Union[str, Sequence[str], None] = 'fd2a58eb98d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sectors', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('sectors', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sectors', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('sectors', 'is_active')
    # ### end Alembic commands ###
