"""update statuses

Revision ID: 87d0d9bd10d8
Revises: 7df0564a7403
Create Date: 2025-07-23 21:24:12.081676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87d0d9bd10d8'
down_revision: Union[str, Sequence[str], None] = '7df0564a7403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'age_restriction',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'age_restriction',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
