"""create Ticket model

Revision ID: 919492e101a2
Revises: 16b4e2881046
Create Date: 2025-08-08 16:24:54.102169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '919492e101a2'
down_revision: Union[str, Sequence[str], None] = '16b4e2881046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('ticket_instance_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('price_net', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('price_gross', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REFUNDED', 'EXPIRED', name='ticket_status'), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_gross >= 0', name='chk_price_gross_nonneg'),
    sa.CheckConstraint('price_net >= 0', name='chk_price_net_nonneg'),
    sa.CheckConstraint('vat_rate >= 1.00', name='chk_vat_rate'),
    sa.ForeignKeyConstraint(['ticket_instance_id'], ['ticket_instances.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('ticket_instance_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    # ### end Alembic commands ###
