"""Edit roles table - add generated always as identity clause

Revision ID: bc74b622656a
Revises: a8fefed6869b
Create Date: 2025-07-10 22:53:30.158401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc74b622656a'
down_revision: Union[str, Sequence[str], None] = 'a8fefed6869b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column('roles', 'id', server_default=None)

    op.execute("""
       ALTER TABLE roles
         ALTER COLUMN id
         ADD GENERATED ALWAYS AS IDENTITY
         (START WITH 1 INCREMENT BY 1)
       """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
