"""add unique index to payments

Revision ID: bfc8a8451d0f
Revises: 1f90a27c7d5a
Create Date: 2025-08-21 13:29:12.534896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc8a8451d0f'
down_revision: Union[str, Sequence[str], None] = '1f90a27c7d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('idempotency_key', sa.String(length=64), nullable=True))
    op.create_index('uq_payments_order_active', 'payments', ['order_id'], unique=True, postgresql_where=sa.text("status IN ('PENDING', 'REQUIRES_ACTION')"))
    op.create_unique_constraint(None, 'payments', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_index('uq_payments_order_active', table_name='payments', postgresql_where=sa.text("status IN ('PENDING', 'REQUIRES_ACTION')"))
    op.drop_column('payments', 'idempotency_key')
    # ### end Alembic commands ###
