"""created organizers model + 1:n addresses

Revision ID: c97d544c9011
Revises: e29a8893e6be
Create Date: 2025-07-15 15:48:44.352705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c97d544c9011'
down_revision: Union[str, Sequence[str], None] = 'e29a8893e6be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizers',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.Text(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('vat_number', sa.String(length=32), nullable=True),
    sa.Column('registration_number', sa.String(length=40), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'registration_number', name='uq_organizers_country_reg_number'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('iban'),
    sa.UniqueConstraint('vat_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizers')
    # ### end Alembic commands ###
