"""Generate refresh session model

Revision ID: e0e5040a2a43
Revises: 9981e69d467d
Create Date: 2025-09-11 01:12:44.264253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0e5040a2a43'
down_revision: Union[str, Sequence[str], None] = '9981e69d467d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_refresh_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('last_used_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_refresh_sessions_expires_at'), 'auth_refresh_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_refresh_sessions_token_hash'), 'auth_refresh_sessions', ['token_hash'], unique=False)
    op.create_index(op.f('ix_auth_refresh_sessions_user_id'), 'auth_refresh_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_refresh_sessions_user_id'), table_name='auth_refresh_sessions')
    op.drop_index(op.f('ix_auth_refresh_sessions_token_hash'), table_name='auth_refresh_sessions')
    op.drop_index(op.f('ix_auth_refresh_sessions_expires_at'), table_name='auth_refresh_sessions')
    op.drop_table('auth_refresh_sessions')
    # ### end Alembic commands ###
