"""Create addresses model

Revision ID: e29a8893e6be
Revises: 004502830781
Create Date: 2025-07-15 14:37:50.122122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e29a8893e6be'
down_revision: Union[str, Sequence[str], None] = '004502830781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('street', sa.Text(), nullable=False),
    sa.Column('postal_code', sa.String(length=12), nullable=False),
    sa.Column('building_number', sa.String(length=10), nullable=False),
    sa.Column('apartment_number', sa.String(length=10), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addresses')
    # ### end Alembic commands ###
