"""update venues table

Revision ID: f66bee764d81
Revises: 1127f16d9a21
Create Date: 2025-07-19 17:21:49.350892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f66bee764d81'
down_revision: Union[str, Sequence[str], None] = '1127f16d9a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('venues_address_id_fkey'), 'venues', type_='foreignkey')
    op.create_foreign_key(None, 'venues', 'addresses', ['address_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues', type_='foreignkey')
    op.create_foreign_key(op.f('venues_address_id_fkey'), 'venues', 'addresses', ['address_id'], ['id'], ondelete='SET NULL')
    op.alter_column('venues', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
