"""Add partial unique index on (user_id, status=PENDING)

Revision ID: fc9c45003118
Revises: 919492e101a2
Create Date: 2025-08-08 17:01:24.332846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc9c45003118'
down_revision: Union[str, Sequence[str], None] = '919492e101a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_orders_user_pending', 'orders', ['user_id'], unique=True, postgresql_where=sa.text("status='PENDING'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_orders_user_pending', table_name='orders', postgresql_where=sa.text("status='PENDING'"))
    # ### end Alembic commands ###
