"""add not null constraint to venue.addresses

Revision ID: fd2a58eb98d0
Revises: 09c62f17a4f0
Create Date: 2025-07-22 00:17:02.019626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd2a58eb98d0'
down_revision: Union[str, Sequence[str], None] = '09c62f17a4f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
